### PR TITLE
[ACA-2987] Use the AuthGuard SSO

### PR DESCRIPTION
**Pull request by mauriziovitale**
**Please check if the PR fulfills these requirements**

> - [ ] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
Not able to login with a user created on keycloak and SSO enabled

**What is the new behaviour?**
The user should be able to login and navigate through the folders

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by adinapitul** [comment]
the fix for ACA-2755 was done in AuthGuardEcm, and does not exist in AuthGuard as far as I can see, so this might regress.

**Comment by mauriziovitale** [comment]
> the fix for [ACA-2755](https://issues.alfresco.com/jira/browse/ACA-2755) was done in AuthGuardEcm, and does not exist in AuthGuard as far as I can see, so this might regress.

Which PR are you referring to? 
There are 10 attached to that issue. From what I can see all related to the SSO stuff this means that should not be correct to use the AuthGuardECM
```
 isPublicUrl(): boolean {
        if (this.isOauthConfiguration()) {
            return this.oauth2Auth.isPublicUrl();
        }
        return false;
    }
```

**Comment by adinapitul** [comment]
this is the only PR done in ADF for ACA-2755 : https://github.com/Alfresco/alfresco-ng2-components/pull/5363

**Comment by mauriziovitale** [comment]
> this is the only PR done in ADF for [ACA-2755](https://issues.alfresco.com/jira/browse/ACA-2755) : [Alfresco/alfresco-ng2-components#5363](https://github.com/Alfresco/alfresco-ng2-components/pull/5363)

It looks like the problem is related to the fact that the loggedin use is present in keycloak and not in activiti so the call fails.

**Pull request closed without merging**
