### PR TITLE
[ACA-2471] - close preview action

### PR DESCRIPTION
**Pull request by dhrn**
## PR Checklist
Please check if your PR fulfills the following requirements:

```
- [x] The commit message follows our guidelines: https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
```

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application / Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?
We are overriding the deletion of the node. If the user performs **delete** operation
in the viewer menu, the viewer is not getting closed.

Issue Number: N/A

## What is the new behavior?
I have created one action to close the preview. so, we can able to dispatch the action from the extension.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

https://issues.alfresco.com/jira/browse/ACA-2471

### CODE REVIEW

**Comment by dhrn** [comment]
@DenysVuika is it looks fine?

**Comment by dhrn** [comment]
@DenysVuika when will I get this on **npm registry**?

**Comment by DenysVuika** [comment]
@dhrn already out as 1.8.3

**Comment by dhrn** [comment]
thanks @DenysVuika

**Pull request merged**
