### PR TITLE
[ACS-9012] Truncate text in saved searches description

### PR DESCRIPTION
**Pull request by MichalKinas**
Add text truncation in saved searches description column, added missing docs in `extension.schema.json` and fixed one small bug in unique saved search name validator. 
https://hyland.atlassian.net/browse/ACS-9012

### CODE REVIEW

**Review by dominikiwanekhyland — APPROVED** [review]

**Review by nikita-web-ua — APPROVED** [review]

**Comment by AleksanderSklorz** [comment]
@MichalKinas I see that actually only description column is truncated but if you check task's title it says about "name" column. Should we truncate name column as well?
image

**Comment by AleksanderSklorz** [comment]
Should we truncate entry in sidebar as well? Actually it doesn't look good because text goes outside of available space: 
image

**Comment by MichalKinas** [comment]
> @MichalKinas I see that actually only description column is truncated but if you check task's title it says about "name" column. Should we truncate name column as well? image

Yes, I think this was misunderstood since I think the original idea was to truncate description column but I think for name it also makes a lot of sense

**Comment by MichalKinas** [comment]
> Should we truncate entry in sidebar as well? Actually it doesn't look good because text goes outside of available space: image

Good point, fixed

**Review by AleksanderSklorz — APPROVED** [review]

**Pull request merged**
