### PR TITLE
[ACA-2994] Snackbar- notifications are displayed with wrong colours

### PR DESCRIPTION
**Pull request by pionnegru**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
[ACA-2994](https://issues.alfresco.com/jira/browse/ACA-2994)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

the alternative to `!import`  is to specify component  class `.mat-snack-bar-container` to prevent colour override

### CODE REVIEW

**Comment by pionnegru** [comment]
I mentioned that using  `.mat-snack-bar-containe.snackbar-error` would also work. From what I  see the colour gets overwritten even if the class is in the same list and I don't see that anything that could lead to an encapsulation problem. I choose `!import`  just because  i've  seen it used in the recent theme update

**Comment by pionnegru** [comment]
Maybe you are right @DenysVuika , I see this was added https://github.com/Alfresco/alfresco-content-app/blob/development/src/app/ui/custom-theme.scss#L51

**Comment by pionnegru** [comment]
@BaptisteMahe any reason including  angular-material-theme in  the custom themes list mentioned above?

**Comment by BaptisteMahe** [comment]
@pionnegru You are right when refactoring the custom theme I messed up the order, those 3 mixins: angular-material-theme, adf-content-services-theme, and adf-core-theme should come first in the custom theme

**Comment by pionnegru** [comment]
thx @BaptisteMahe, I'll change those

**Pull request merged**
