### PR TITLE
[ACS-8160][ACA] Update style of tag component in info drawer

### PR DESCRIPTION
**Pull request by tamaragruszka**
**JIRA ticket link or changeset's description**
https://hyland.atlassian.net/browse/ACS-8160

needs merged 
https://github.com/Alfresco/alfresco-ng2-components/pull/10226

### CODE REVIEW

**Review by DenysVuika — APPROVED** [review]

**Review by swapnil-verma-gl — APPROVED** [review]

**Comment by AleksanderSklorz** [comment]
There is some issue that I need to click X button twice to remove tag: 

https://github.com/user-attachments/assets/72b35ef3-5acd-4ad1-8a94-479bc0c5d32c

**Comment by AleksanderSklorz** [comment]
I can't find a tag after unassigning it from file 

https://github.com/user-attachments/assets/9460ed69-4aa2-49d5-b540-c79bc8ca92e2

**Comment by AleksanderSklorz** [comment]
"View x more" button is not displayed until you refresh page. It should be displayed if tags does not fit to available space. Actually you need refresh page to see that button but it should be visible without refreshing: 

https://github.com/user-attachments/assets/d759e629-9bf9-4c34-ad95-d4f2da7df030

**Comment by tamaragruszka** [comment]
@AleksanderSklorz issues you reported are coming from ADF, change for ACA only provide styles for the component

**Comment by AleksanderSklorz** [comment]
> @AleksanderSklorz issues you reported are coming from ADF, change for ACA only provide styles for the component

Double tested and in acadev env it works correctly but on this branch does not.

**Comment by tamaragruszka** [comment]
@AleksanderSklorz

**Comment by AleksanderSklorz** [comment]
> I can't find a tag after unassigning it from file
> 
>  Screen.Recording.2024-10-07.at.12.44.20.mov

This is not addressed and I can see that on remote environment this can't be reproduced, please have a look

**Comment by tamaragruszka** [comment]
> > I can't find a tag after unassigning it from file
> > Screen.Recording.2024-10-07.at.12.44.20.mov
> 
> This is not addressed and I can see that on remote environment this can't be reproduced, please have a look. NOTE: When you type full tag's name then tag is found but if you type only part of name then can't be found


https://github.com/user-attachments/assets/8adc2fd0-7ca0-4679-baf3-c7e554ff4b4f

**Comment by AleksanderSklorz** [comment]
> > > I can't find a tag after unassigning it from file
> > > Screen.Recording.2024-10-07.at.12.44.20.mov
> > 
> > 
> > This is not addressed and I can see that on remote environment this can't be reproduced, please have a look. NOTE: When you type full tag's name then tag is found but if you type only part of name then can't be found
> 
>  Screen.Recording.2024-10-14.at.10.49.30.mov

I see you did incorrect steps because you save tags after remove but you should not save them. Please do with the same steps then you should be able to reproduce this

**Comment by AleksanderSklorz** [comment]
> > > > I can't find a tag after unassigning it from file
> > > > Screen.Recording.2024-10-07.at.12.44.20.mov
> > > 
> > > 
> > > This is not addressed and I can see that on remote environment this can't be reproduced, please have a look. NOTE: When you type full tag's name then tag is found but if you type only part of name then can't be found
> > 
> > 
> > Screen.Recording.2024-10-14.at.10.49.30.mov
> 
> I see you did incorrect steps because you save tags after remove but you should not save them. Please do with the same steps then you should be able to reproduce this

I checked it too now and seems working, not sure why it was not working previously

**Review by AleksanderSklorz — APPROVED** [review]

**Review by MichalKinas — APPROVED** [review]

**Pull request merged**
