### PR TITLE
Release 2.2.0

### PR DESCRIPTION
**Pull request by DenysVuika**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [x] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

- new: script to update all package versions
- new: script to generate all necessary reports
- release changes

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Review by eromano — CHANGES_REQUESTED** [review]
ADF dependencies need to be update

**Review by mauriziovitale — APPROVED** [review]

**Review by eromano — APPROVED** [review]

**Review by montgolfiere — CHANGES_REQUESTED** [review]
@DenysVuika Will you also include https://github.com/Alfresco/alfresco-content-app/pull/1874 (if not already) ? ( cc @VitoAlbano @ursedaniel )

**Comment by DenysVuika** [comment]
@montgolfiere yes, it's a rebased PR after all other ones got merged

**Review by montgolfiere — COMMENTED** [review]
Thanks

**Pull request merged**
