### PR TITLE
[ACS-7331 ] - View details sidebar

### PR DESCRIPTION
**Pull request by jacekpluta**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [ ] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

**What is the new behaviour?**

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by nikita-web-ua** [comment]
Looks good, but for the edit mode looks a bit strange with grey background and underline, is that expected? 
And `adf-card-view-selectitem` looks not aligned with other styles  

Screenshot 2024-03-26 at 08 46 06

**Comment by MichalKinas** [comment]
Comments section looks broken still
Zrzut ekranu 2024-03-26 o 10 11 04

**Comment by MichalKinas** [comment]
Placeholder for categories looks misaligned
Zrzut ekranu 2024-03-26 o 10 14 11

**Review by MichalKinas — CHANGES_REQUESTED** [review]
Please check the issues from screenshots

**Pull request merged**
