### PR TITLE
[ACA-4287] Fix Reload library

### PR DESCRIPTION
**Pull request by dhrn**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)

https://alfresco.atlassian.net/browse/ACA-4287

**What is the new behaviour?**

fixed

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by adinapitul** [comment]
this problem does NOT happen in ACA
this problem does NOT happen in ADW in My Libraries or Favorite Libraries
it only happens in ADW in All Libraries - which is only present in ADW.
so, why should a change in ACA be required?

**Comment by dhrn** [comment]
ADW is depends on the underlying event hook from ACA. we don't have any other approach other than modifying the current ACA implementation. you can correct me if i am wrong. I will discuss with @DenysVuika to avoid this problems in future and  give more capability to extension users.

**Comment by pionnegru** [comment]
and [these](https://github.com/Alfresco/alfresco-content-app/blob/develop/src/app/components/libraries/libraries.component.ts#L57-L59 ) don't do the same thing?
maybe we ned to retire them and use thee actions.

**Comment by dhrn** [comment]
No this didn't help. we have own layout.

**Comment by pionnegru** [comment]
I'm saying maybe we should remove [these](https://github.com/Alfresco/alfresco-content-app/blob/develop/src/app/components/libraries/libraries.component.ts#L57-L59) and use ReloadLibraryAction also

**Comment by dhrn** [comment]
yes  you are correct. also planning to move the hooks to aca shared library like [this](https://github.com/Alfresco/alfresco-content-app/compare/dev-dhrn-move-hooks)

**Comment by dhrn** [comment]
We can do that as well

**Comment by dhrn** [comment]
Hmm, that is good approach. we can do that. Wondering how will impact the other community extension. so eventually we will remove all the subject based hook?

**Comment by dhrn** [comment]
addressed in #2052

**Pull request closed without merging**
