### PR TITLE
[ACA-2210] Version Dialog - update button text

### PR DESCRIPTION
**Pull request by pionnegru**
## PR Checklist
Please check if your PR fulfills the following requirements:

```
- [x] The commit message follows our guidelines: https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
```

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application / Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

**Buttons have incorrect text on Upload new version dialog**
See [ACA-2210](https://issues.alfresco.com/jira/browse/ACA-2210) for more details.

## What is the new behavior?

Wording update, use "Cancel" instead of "Close" for the cancel button.

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by binduwavell** [comment]
I assume this is also incomplete given how the description is filled out and yet it does not have the new incomplete flag?

**Comment by binduwavell** [comment]
Thanks for updating description, this is great! Unfortunately I can’t see linked JIRA, may be same one that I commented about on different PR.

**Comment by DenysVuika** [comment]
@binduwavell the https://issues.alfresco.com/jira/browse/ACA-2210 ticket is public, should not require Jira account to view the content, just tried with non-authenticated browser with no VPN and it works fine for me. Does it require you to log in?

**Comment by binduwavell** [comment]
I just checked and it was still not visible. I chef 5 seconds later and I could see it :)

**Pull request merged**
