### PR TITLE
[ACS-6211] Resolved UI alignment issue in create rule dialog

### PR DESCRIPTION
**Pull request by swapnil-verma-gl**
**Please check if the PR fulfills these requirements**

> - [x] The commit message follows our [guidelines](https://github.com/Alfresco/alfresco-ng2-components/wiki/Commit-format)
> - [ ] Tests for the changes have been added (for bug fixes / features)
> - [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

> - [x] Bugfix
> - [ ] Feature
> - [ ] Code style update (formatting, local variables)
> - [ ] Refactoring (no functional changes, no api changes)
> - [ ] Build related changes
> - [ ] Documentation
> - [ ] Other... Please describe:

**What is the current behaviour?** (You can also link to an open issue here)
Create rule dialog had minor UI alignment issues

**What is the new behaviour?**
Fixed alignment issues

**Does this PR introduce a breaking change?** (check one with "x")

> - [ ] Yes
> - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by AleksanderSklorz** [comment]
@swapnil-verma-gl there are still some options which has not aligned parameters: 
image

See - "select an action" and "Aspect" fields are not aligned (are not in the same line)

**Comment by swapnil-verma-gl** [comment]
> @swapnil-verma-gl there are still some options which has not aligned parameters: image
> 
> See - "select an action" and "Aspect" fields are not aligned (are not in the same line)

That is a change that would need to be done in ADF, since the component being used here for the dropdown comes from ADF ([card-view-selectitem.component](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html#L5)). If we want, I can raise another PR for it in the ADF repo for the fix once the ADF code freeze is over

**Comment by AleksanderSklorz** [comment]
> > @swapnil-verma-gl there are still some options which has not aligned parameters: image
> > See - "select an action" and "Aspect" fields are not aligned (are not in the same line)
> 
> That is a change that would need to be done in ADF, since the component being used here for the dropdown comes from ADF ([card-view-selectitem.component](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html#L5)). If we want, I can raise another PR for it in the ADF repo for the fix once the ADF code freeze is over

@swapnil-verma-gl yes, please raise fix for this too if possible. I think it was one of main purposes of raising this jira. If you check Akash's video (for example 9th second) attached to this jira then you can see he is showing that these fields are unaligned. 

I think as part of that jira we should ensure that all parameters are aligned properly for their actions.

**Comment by swapnil-verma-gl** [comment]
> > > @swapnil-verma-gl there are still some options which has not aligned parameters: image
> > > See - "select an action" and "Aspect" fields are not aligned (are not in the same line)
> > 
> > 
> > That is a change that would need to be done in ADF, since the component being used here for the dropdown comes from ADF ([card-view-selectitem.component](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html#L5)). If we want, I can raise another PR for it in the ADF repo for the fix once the ADF code freeze is over
> 
> @swapnil-verma-gl yes, please raise fix for this too if possible. I think it was one of main purposes of raising this jira. If you check Akash's video (for example 9th second) attached to this jira then you can see he is showing that these fields are unaligned.
> 
> I think as part of that jira we should ensure that all parameters are aligned properly for their actions.

@AleksanderSklorz Raised [this PR](https://github.com/Alfresco/alfresco-ng2-components/pull/9101) for fixing the UI issues in ADF

**Review by DominikIwanek — APPROVED** [review]

**Review by MichalKinas — APPROVED** [review]

**Comment by swapnil-verma-gl** [comment]
> > > > @swapnil-verma-gl there are still some options which has not aligned parameters: image
> > > > See - "select an action" and "Aspect" fields are not aligned (are not in the same line)
> > > 
> > > 
> > > That is a change that would need to be done in ADF, since the component being used here for the dropdown comes from ADF ([card-view-selectitem.component](https://github.com/Alfresco/alfresco-ng2-components/blob/develop/lib/core/src/lib/card-view/components/card-view-selectitem/card-view-selectitem.component.html#L5)). If we want, I can raise another PR for it in the ADF repo for the fix once the ADF code freeze is over
> > 
> > 
> > @swapnil-verma-gl yes, please raise fix for this too if possible. I think it was one of main purposes of raising this jira. If you check Akash's video (for example 9th second) attached to this jira then you can see he is showing that these fields are unaligned.
> > I think as part of that jira we should ensure that all parameters are aligned properly for their actions.
> 
> @swapnil-verma-gl this issue is resolved with newest changes now but I can see other places which are not aligned like:
> 
> image
> "Destination folder" is a bit not aligned if you compare it with left field.

Thank you @AleksanderSklorz. The alignment issue has been resolved with [this](https://github.com/Alfresco/alfresco-ng2-components/pull/9101/commits/9b8001578fb3f4876fb38c14aaf5dfe941b51184) commit

**Pull request merged**
