### PR TITLE
[ACA-2199] Upload Version - granular permission  

### PR DESCRIPTION
**Pull request by pionnegru**
## PR Checklist
Please check if your PR fulfills the following requirements:

```
- [x] The commit message follows our guidelines: https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
```

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application / Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: [ACA-2199](https://issues.alfresco.com/jira/browse/ACA-2199)

## What is the new behavior?

- add unit tests for evaluators
- dedicated evaluator for "Upload Version" action (previously used "Versions" one)

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
Upload Version action on an unlocked file should be available only for users with "Update" permissions

### CODE REVIEW

**Comment by binduwavell** [comment]
Is there a reason that the checklists, etc in the PR description are not completed?

**Comment by binduwavell** [comment]
Should there be a test for `canUploadVersion()`?

**Comment by DenysVuika** [comment]
@binduwavell added some tests, thanks for pointing out. We will add more of them soon.

**Comment by binduwavell** [comment]
Thanks much!

**Pull request merged**
