### PR TITLE
UrlEncoding search functionality

### PR DESCRIPTION
**Pull request by M3noetius**
## PR Checklist
Please check if your PR fulfills the following requirements:

```
- [ x] The commit message follows our guidelines: https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
```

## PR Type
What kind of change does this PR introduce?

```
[x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application / Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #822

## What is the new behavior?
The user could not search for files with special characters

## Does this PR introduce a breaking change?
```
[ ] Yes
[ x] No
```

### CODE REVIEW

**Comment by DenysVuika** [comment]
Great stuff! Note, however, that the change needs to be done against "development" branch, it has the most recent code so far

**Comment by M3noetius** [comment]
Sadly in the process of trying to comply with the code of conduct and the git process we got busted by a previous pull request ! So this is a duplicate :/

**Comment by DenysVuika** [comment]
No worries, thanks for contribution anyway. 👍

**Comment by M3noetius** [comment]
Thanks !:) Feel free to close the PR !

**Comment by john-knowles** [comment]
@M3noetius - what is the best way to contact you directly?

**Comment by M3noetius** [comment]
@john-knowles Via email would be great. Here it is. gdtsek@gmail.com

**Pull request closed without merging**
