### PR TITLE
[ACA-2198 ACA-2206]  Node version - align dialog with XD

### PR DESCRIPTION
**Pull request by pionnegru**
## PR Checklist
Please check if your PR fulfills the following requirements:

```
- [x] The commit message follows our guidelines: https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
```

## PR Type
What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Application / Infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number:

https://issues.alfresco.com/jira/browse/ACA-2198
https://issues.alfresco.com/jira/browse/ACA-2206

## What is the new behavior?

align version form design with XD

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by binduwavell** [comment]
Please include description explaining how this resolves the issues in the linked JIRA tickets.

**Comment by binduwavell** [comment]
Consider adding test to ensure upload button is enabled when form is displayed given that defaults for everything required are already provided.

**Comment by binduwavell** [comment]
I think `en.json` is still wrong.

**Comment by binduwavell** [comment]
This looks solid now, thanks. One final comment, John, I can’t see the linked JIRAs in order to consider the design this is intending to reflect.

**Comment by john-knowles** [comment]
> This looks solid now, thanks. One final comment, John, I can’t see the linked JIRAs in order to consider the design this is intending to reflect.

JIRAs linked to ACA-213?

**Comment by binduwavell** [comment]
I can’t access any of the three linked JIRAs.

**Comment by john-knowles** [comment]
Incognito in Chrome I can get to: https://issues.alfresco.com/jira/browse/ACA-213 and its sub-tasks https://issues.alfresco.com/jira/browse/ACA-2206 https://issues.alfresco.com/jira/browse/ACA-2198

**Comment by binduwavell** [comment]
Thanks for checking. Is flaky for me but if I try enough times it does work. I’m on my phone. I’ll debug on this side. Thanks again!

**Pull request merged**
